### ISSUE TITLE
GUI version needs zenity on KDE

### ISSUE THREAD

**Issue by apinter** [DarthWound/tumbleweed-updater#1]
Was just checking the updater on KDE and noticed that the gui version needs zenity to be installed. I would check it in the installer for zentiy (```rpm -qa | grep zenity | wc -l```) or (maybe, probably the zenity check is better) check the desktop type and if anything other than gnome or the forks just install it (```echo $DESKTOP_SESSION```)

**Comment by DarthWound** [comment]
Install script should already check requirements:

https://github.com/DarthWound/tumbleweed-updater/blob/master/install-en.sh#L28

**Comment by apinter** [comment]
Dang, had to install manually in my case ::) 

Closing then
